---
name: CI

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
      - name: Install linting tools
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck yamllint python3-pip
          npm install -g markdownlint-cli
          install_script_url="https://raw.githubusercontent.com/"
          install_script_url+="terraform-linters/tflint/master/install_linux.sh"
          curl -s "${install_script_url}" | bash
          python3 -m pip install --user pre-commit
      - name: Lint
        run: make lint
      - name: Validate
        run: make validate
      - name: Test
        run: make test
